### ISSUE TITLE
URLs are not turned into links on the website

### ISSUE THREAD

**Issue by stof** [unicode-org/icu-docs#19]
When looking at the readme on github, we have links for URLs which are not using specific markdown links, thanks to the auto-linking features of Github-Flavored Markdown: 
![image](https://user-images.githubusercontent.com/439401/104300108-58806780-54c6-11eb-9d3c-8335c5f2986e.png)

However, when looking at the website on https://unicode-org.github.io/icu-docs/, autolinking is not applied: 
![image](https://user-images.githubusercontent.com/439401/104300214-79e15380-54c6-11eb-980a-2c3b20611bd0.png)

It would be great to use a markdown parser implementing GFM for the website. Otherwise, the markdown files need to be updated to use explicit links everywhere.

**Comment by hugovdm** [comment]
Thanks for bringing this to our attention!

I noticed the links right next to the bullets are broken too: the problem being that these directories do not have an index page (e.g. "index.md", "index.html"). I'm not sure what we want to do with those.

* Changing the markdown processor: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll - I've not yet found clear proof that kramdown is the default, but I agree we should try setting it to CommonMark anyway.
* Fixing the ./design/, ./docs/pres/, etc links: I'm not yet sure what we want to do with those. Some options:
  * Make these links explicitly point at github.com instead of unicode-org.github.io?
  * Create explicit directory listings? e.g. https://stackoverflow.com/questions/39048654/how-to-enable-directory-indexing-on-github-pages

**Comment by markusicu** [comment]
Moved to https://unicode-org.atlassian.net/browse/ICU-21681

I will close the issue tracker on this repo.
